behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 40960
      learning_rate: 0.0005
      beta: 0.005 # (0.0001 - 0.01)
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 20
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 2048
      num_layers: 6
      vis_encode_type: nature_cnn
    reward_signals:
      extrinsic:
        gamma: 0.85
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 25000
      team_change: 100000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.65
      initial_elo: 1200.0